image: registry.freedesktop.org/libnice/libnice/build-tools:centos-7
stages:
 - build
 - test

build autotools:
 stage: build
 except:
  - schedules
 before_script:
  - yum install -y net-tools
 script:
  - ifconfig
  - export BUILD_ID="libnice-$CI_JOB_NAME_$CI_COMMIT_SHA-$CI_JOB_ID"
  - export PREFIX="$(pwd)/prefix-$BUILD_ID"
  - export MAKEFLAGS="-j4"
  - mkdir "$PREFIX"
  - ./autogen.sh --prefix="$PREFIX" --enable-compile-warnings=error --enable-gtk-doc --enable-introspection
  - make
  - make install
 artifacts:
   untracked: true

test autotools:
  stage: test
  except:
    - schedules
  dependencies:
    - build autotools
  before_script:
   - yum install -y net-tools
  script:
    - ifconfig
    - make check
  artifacts:
    when: always
    paths:
      - config.log
      - nice/test-suite.log
      - random/test-suite.log
      - tests/test-suite.log
      - stun/tests/test-suite.log

distcheck autotools:
  stage: test
  except:
    - schedules
  dependencies:
    - build autotools
  before_script:
   - yum install -y net-tools
  script:
    - ifconfig
    - make distcheck
  artifacts:
    paths:
      - libnice-*.tar.gz

build meson:
  image: 'fedora'
  stage: build
  variables:
    PREFIX: "${CI_PROJECT_DIR}/libnice-prefix"
    DEPENDENCIES: >
      meson
      gnutls-devel
      gupnp-igd-devel
      glib2-devel
      gobject-introspection-devel
      gstreamer1-devel
      redhat-rpm-config
      gtk-doc
  except:
    - schedules
  before_script:
    - dnf install -y ${DEPENDENCIES}
    - mkdir -p "${CI_PROJECT_DIR}"
  script:
    - meson --werror --warnlevel 2 -Dgtk_doc=enabled --prefix=$PREFIX build/
    - ninja -C build/
  artifacts:
    paths:
      - build/

test meson:
  image: 'fedora'
  stage: test
  allow_failure: true
  dependencies:
    - build meson
  except:
    - schedules
  variables:
   PREFIX: "${CI_PROJECT_DIR}/libnice-prefix"
   DEPENDENCIES: >
     meson
     net-tools
     gnutls-devel
     gupnp-igd-devel
     glib2-devel
     gobject-introspection-devel
     gstreamer1-devel
     redhat-rpm-config
      gtk-doc
  before_script:
    - dnf install -y ${DEPENDENCIES}
    - mkdir -p "${CI_PROJECT_DIR}"
  script:
    - ifconfig
    - meson test -C build --print-errorlogs
  artifacts:
    when: on_failure
    paths:
      - build/meson-logs/

doc-and-install meson:
  stage: test
  image: fedora
  dependencies:
    - build meson
  except:
    - schedules
  variables:
    PREFIX: "${CI_PROJECT_DIR}/libnice-prefix"
    DEPENDENCIES: >
     meson
     net-tools
     gnutls-devel
     gupnp-igd-devel
     glib2-devel
     gobject-introspection-devel
     gstreamer1-devel
     redhat-rpm-config
     gtk-doc
  before_script:
    - dnf install -y ${DEPENDENCIES}
    - mkdir -p "${CI_PROJECT_DIR}"
  script:
    - ninja -C build libnice-doc
    - ninja -C build/ install
    - ls -lR ${PREFIX}
  artifacts:
    paths:
      - build/docs/reference/libnice/html/

submit-to-coverity:
 image: registry.freedesktop.org/libnice/libnice/build-tools/coverity:2017.07
 stage: build
 only:
  - schedules
 script:
  - ./autogen.sh --prefix="$PREFIX" --disable-gtk-doc --disable-introspection
  - make clean
  - export PATH="$PATH:/root/cov-analysis-linux64-2017.07/bin"
  - cov-build --dir cov-int make -j4
  - tar czvf libnice.tgz cov-int
  - curl --form token=$COVERITY_TOKEN --form email=olivier.crete@ocrete.ca --form file=@libnice.tgz --form version="${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}" --form description="CI weekly run" https://scan.coverity.com/builds?project=libnice
